### ISSUE TITLE
Issue with classes_num for training stage ! 

### ISSUE THREAD

**Issue by oggyfaker** [LouieShao/1st-Place-Solution-in-Google-Universal-Image-Embedding#3]
Hi i have some confusion with your preprocessing dataset. 

I see something wrong with first-stage training, when you got the shoppee dataset and you have this line `classes_num += np.unique(label_list).shape[0]`. After that you continue using the same code for Alibaba Good dataset (I think it should be `classes_num += np.unique(label_ali).shape[0]` ). 

After that you remove all element in list of `file_list=[]` and `label_list=[]` and just add DeepFashion alonely. And the classes_num for Deepfashion is also not correct, it should be 16 class unique.

Hope to see your response !

**Comment by ShihaoShao-GH** [comment]
Yes. The `class_num` is wrong. It is higher than the actual `class_num`. I write like that because I need to frequently try different datasets during the competition, so I basically choose a big enough number. It will not cause bugs but indeed it should get fixed to avoid unneccessary memory and computation overhead.
